# Generated by Django 5.2.14 on 2026-05-10 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20260510_1605'),
        ('posts', '0005_auto_20250511_0104'),
    ]

    operations = [
    ]
